### ISSUE TITLE
file URLs and mailto with IP addresses throw exceptions

### ISSUE THREAD

**Issue by kristomu** [chmike/CxxUrl#13]
DOS file:// URLs give an invalid port exception, and mailto gives a path exception. These are both valid URLs.

To reproduce, insert the following tests to main.cpp:

```
test_parse("file://C:/WINDOWS/WIN.COM", scheme, "file");
test_parse("mailto:foo@[192.168.0.2]", scheme, "mailto");
```

Both tests will fail due to exceptions being thrown. In contrast (and as expected), Unix file:// URLs and mailto with hostnames pass:

```
test_parse("file:///etc/passwd", scheme, "file");
test_parse("mailto:foo@example.com", scheme, "mailto");
```

**Comment by chmike** [comment]
Thank you for reporting the problems you found. There are two different problems. 

1. File path don’t have a host name part. The URL should thus be `file:///C:/WINDOWS/WIN.COM` with three /. See [this wikipedia page on the file URI scheme](https://en.wikipedia.org/wiki/File_URI_scheme).
2. The destination address given with `mailto` URL is a path. There is no host part. The problem is because [] are not allowed in the path. The problem is fixed by replacing [ with %5C and ] with %5D. Note also, if I remember well, that by convention square brackets are only used for IPv6 addresses. IPv4 addresses don’t have brackets. 

Thus it seam that there is no error in the library. The paths you provided are not valid URLs.

**Comment by kristomu** [comment]
Regarding the mailto URL, from https://datatracker.ietf.org/doc/html/rfc3696, section 3:

   Contemporary email addresses consist of a "local part" separated from
   a "domain part" (a fully-qualified domain name) by an at-sign ("@").
   The syntax of the domain part corresponds to that in the previous
   section.  The concerns identified in that section about filtering and
   lists of names apply to the domain names used in an email context as
   well.  **The domain name can also be replaced by an IP address in
   square brackets**, but that form is strongly discouraged except for
   testing and troubleshooting purposes.

So although it's discouraged, IPv4 user@[192.168.0.1] type URIs are valid, to my knowledge.
Another reference that explicitly mentions this format can be found here: https://www.serviceobjects.com/blog/ip-address-vs-domain-in-an-email-address/

**Comment by chmike** [comment]
I see. Thanks for the clarification. The problem is that the square brackets are not allowed in the path part of the URL.  See [the URL encoding RFC](https://datatracker.ietf.org/doc/html/rfc3986#appendix-A). 

RFC2368 doesn't make clear that the email address list is in the path part of the URL, but it must be to remain a valid URL. Also it seam that the reference documentation overlooked that email address might have square brackets which are not allowed in the path part of an URL.

Thus the problem is solved by percent encoding the square brackets around IP address.

If you are satisfied by the answer, I invite you to close the issue.

**Comment by kristomu** [comment]
This is definitely not my area of expertise, but from what I can glean from the RFCs, it seems that mailto URLs/URIs don't follow the standard pattern. RFC 822 3.4.6 states that the presence of [ and ] in the domain part of the address indicates a domain-literal which overrides DNS lookups; and then RFC 6068 2. states that the format of mailto is:

```
      mailtoURI    = "mailto:" [ to ] [ hfields ]
      to           = addr-spec *("," addr-spec )
      hfields      = "?" hfield *( "&" hfield )
      hfield       = hfname "=" hfvalue
      hfname       = *qchar
      hfvalue      = *qchar
      addr-spec    = local-part "@" domain
      local-part   = dot-atom-text / quoted-string
      domain       = dot-atom-text / "[" *dtext-no-obs "]"
      dtext-no-obs = %d33-90 / ; Printable US-ASCII
                     %d94-126  ; characters not including
                               ; "[", "]", or "\"
      qchar        = unreserved / pct-encoded / some-delims
      some-delims  = "!" / "$" / "'" / "(" / ")" / "*"
                   / "+" / "," / ";" / ":" / "@"
```

This doesn't seem to reference a path field.

I'm using CxxUrl to validate mail addresses found in text files or on the web, and ultimately the problem is that mailto addresses that I find and that seem to be valid according to the RFCs are rejected by CxxUrl. I know too little about the detailed specs of URLs to say just why that happens or if the specs contradict each other; I just observe that it happens.

**Comment by chmike** [comment]
Indeed, a `mailto` URI is not compatible with a `http` or `https` URL because of the square brackets. 

This is the main syntax of a URL (https://datatracker.ietf.org/doc/html/rfc3986#appendix-A).
```
URI            = scheme ":" hier-part [ "?" query ] [ "#" fragment ]
hier-part      = "//" authority path-abempty
                       / path-absolute
                       / path-rootless
                       / path-empty
. . .
path-rootless  = segment-nz *( "/" segment )
segment-nz     = 1*pchar
pchar          = unreserved / pct-encoded / sub-delims / ":" / "@"
unreserved     = ALPHA / DIGIT / "-" / "." / "_" / "~"
sub-delims     = "!" / "$" / "&" / "'" / "(" / ")" / "*" / "+" / "," / ";" / "="

``` 
Since a `mailto` URI doesn't start with "//", it has no `authority` part. Since it also doesn't start with "/", it must be a `path-rootless`. As you can see, the "[" and "]" are not `pchar`. They can't thus appear in a `segment-nz`. Thus `mailto` URI containing "[" or "]" are not valid URL. 

I don't know why square brackets are disallowed in URLs. 

Until the specification disagreement is fixed, I will stick to the URL specification.

**Comment by kristomu** [comment]
Okay; could you make a note in the README that URIs that don't follow the URL standards might not be correctly parsed in all cases, so that other users will be aware of it?

And then I'll just call this a feature request: if you feel like it later, parsing of common non-URL URIs would be a nice thing to have.

**Comment by chmike** [comment]
I have added the link to the RFC and a warning in the README as you suggest.

Regarding parsing non-URL URIs, I can consider adding Pull Requests. I currently don’t have the time and motivation to add support of common non-URL. You could derive your own library to parse `mailto` URIs from this library.

**Comment by kristomu** [comment]
If I end up making a change to that effect, I'll add a PR. Thanks.
